#!/bin/bash

# Change name of files starting with the underscore symbol.
# Those files are not copied by jekyll.

for i in `ls ../html | grep -E '^_.*'`; do

   echo "[II] working for file: $i" 

   old_name=`echo $i | sed -e 's/\..*//g'`
   new_name="underscore"$old_name""
   
   mv ../html/$i ../html/"underscore"$i

   for j in `ls ../html`; do

      if [ -d ../html/$j ]; then
         continue
      fi

      if ! [ `cat ../html/$j | grep $old_name | wc -l` == 0 ]; then 

         cat ../html/$j | LC_ALL=C sed -e "s|$old_name|$new_name|g" > .tmp 
         cat .tmp > ../html/$j
         rm .tmp
      fi

   done

done
